#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# virt desktop names
bspc monitor -d Browser Term Game MC Edu Win10

# them g a p s
bspc config border_width         2 
bspc config window_gap          12
bspc config top_padding         15
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0

#mouse thangs (not sure if this breaks Kdenlive)
bspc config pointer_follows_focus true 
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#ff79c6
bspc config normal_border_color \#6272a4
bspc config border_radius 10

#bspc rule -a makes certain applications floating (not sure how effective this is lol)
bspc rule -a Gimp       desktop='^8' state=floating follow=on
bspc rule -a Chromium   desktop='^2'
bspc rule -a mplayer2   state=floating
bspc rule -a Kupfer.py  focus=on
bspc rule -a Sxiv       state=floating center=true focused=on
bspc rule -a Screenkey  manage=off
bspc rule -a multimc    state=floating center=true focused=on
bspc rule -a virt-manager state=floating center=true focused=on

#Autstart programs 
killall sxhkd
sxhkd &
killall picom
pgrep picom || picom -b --experimental-backends &
killall kited
#lxappearance & (no longer needed because xsetroot)
kitty &
# Above starts kitty, below makes notifs work
killall notification-daemon
/usr/lib/notification-daemon-1.0/notification-daemon &
# This gives the cursor theme (somehow) 
xsetroot -cursor_name left_ptr &

## Wallpapers
# Sweet wall
#feh --bg-scale /home/dannyarch/.local/share/wallpapers/Sweet-Wallpapers/Sweet-space.png
#Moutains with a nice sky, very blue
#feh --bg-scale $HOME/Downloads/wallpapers-master/0062.jpg
# Kobayashi Car
feh --bg-scale $HOME/Downloads/wallpapers-master/smallhead.png

$HOME/.config/polybar/launch.sh 
setxkbmap -option caps:escape &
